### ISSUE TITLE
Problem with LD_LIBRARY_PATH & libreadline.so

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/ruby-buildpack#35]
According to [Ruby buildpack source](https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/cloud_foundry/language_pack/ruby.rb), it sets `$HOME/ld_library_path` as its default LD_LIBRARY_PATH.

```
  def setup_profiled
    original_setup_profiled

    set_env_default  "LD_LIBRARY_PATH", "$HOME/ld_library_path"
  end
```

And `app/ld_library_path/libreadline.so.5` is symlink to `/usr/lib/libreadline.so` [code](https://github.com/cloudfoundry/ruby-buildpack/blob/master/lib/cloud_foundry/language_pack/helpers/readline_symlink.rb)

```
mkdir -p #{ARGV[0]}/ld_library_path
ln -s /usr/lib/libreadline.so #{ARGV[0]}/ld_library_path/libreadline.so.5
```

However as confirmed, `libreadline.so` doesn't exist under `/usr/lib/` in cflinuxfs2 stack,

lucid64: /usr/lib/libreadline.so
cflinuxfs2: /usr/lib/x86_64-linux-gnu/libreadline.so

Those Ruby apps which has dependency on `libreadline.so` won't work with cflinuxfs2 stack.

**Comment by jtarchie** [comment]
After thorough investigation, we've determined that this not a readline problem.
It turns out that Jekyll was following a non-existent libreadline symlink when generating the static files. This is because the buildpack puts a symlink in place for the lucid64, which is not needed on cflinuxfs2.

When @nicwilliams disabled auto-generation, this caused the dead symlink to be followed, resulting in the above error.

libreadline works fine on CloudFoundry. We're not concerned about the dead symlink as it'll be going away with the death of lucid64. However, it's worth it to note that other issues would have followed had the libreadline symlink existed. For example, Jekyll would have attempted to copy in the rubies to the generated content.

When Jekyll is run on CF, care should be taken to ensure that the source directory is not the root directory. This is because CF will add files to /app, which then get traversed by Jekyll.

Closing. We'll remove libreadline symlink when lucid64 support is [officially dropped](https://www.pivotaltracker.com/story/show/96135874) from the buildpacks.
