### ISSUE TITLE
Warning about Procfile not existing, webbrick

### ISSUE THREAD

**Issue by matobinder** [cloudfoundry/ruby-buildpack#38]
So I think this is just a "noisy" warning, not even sure if means anything.

When ever I do a "cf push" of my app into Cloud Foundry, I get the following warning.
###### WARNING:
       No Procfile detected, using the default web server (webrick)
       https://devcenter.heroku.com/articles/ruby-default-web-server

My manifest.yaml file has
  command: rackup -p $PORT --server thin ./config.ru
And indeed I have no Procfile.

I can also verify it is using thin, not webbrick. So where is this error coming from?
I can make it go away, by putting that same line from my manifest.yaml file into the Procfile. 

Either way, it is not using Webbrick.

Last question, is there a better post things that are more of questions than actual issues? This could just me not knowing what I am doing, I am new to CF in general.

**Comment by jtarchie** [comment]
@matobinder for general questions, please feel free to join the [mailing list](http://lists.cloudfoundry.org). There are lot active users of Cloud Foundry that can help with support and setup of apps, deployments, etc.

As for your issue above, the buildpack does not detect the start command in your application code, so it tries to supply one. When you specify a start command in your `manifest.yml`, CF gives that priority over the buildpack. This is expected behavior. 

Let us know if you have any other questions.
