### ISSUE TITLE
Ruby and JRuby CVEs

### ISSUE THREAD

**Issue by will-gant** [cloudfoundry/ruby-buildpack#448]
Hi there. I'm an engineer from the consultancy EngineerBetter, currently working with SAP's [Control Plane team](https://github.com/orgs/SAP/teams/cf-controlplane). We've been running security scans with [Black Duck](https://www.blackducksoftware.com/) on various dependencies, including buildpacks, and one of those scans has revealed a number of CVEs in dependencies of the ruby-buildpack. This issue only reports those concerning versions of dependencies that are still bundled in the latest release of the ruby-buildpack (at the time of writing, v1.8.53).

The vulnerabilities are described in a series of tables below. The first table is three versions of ruby that are 'top-level' dependencies of the buildpack. Each subsequent table is for a top-level dependency that has _sub-dependencies_ with CVEs.

In one instance the issue raised is actually a 'BDSA' (Black Duck Security Advisory), which is a proprietary type of advisory whose details aren't published to the wider world. I've reproduced the details of that below the table in question.

<h2>Top-level dependencies</h2>

Dependency | Version | CVEs | Minimum recommended version bump
-- | -- | -- | --
Ruby | 3.0.3 | [CVE-2022-28738](https://www.ruby-lang.org/en/news/2022/04/12/double-free-in-regexp-compilation-cve-2022-28738), [CVE-2022-28739](https://www.ruby-lang.org/en/news/2022/04/12/buffer-overrun-in-string-to-float-cve-2022-28739) | 3.0.4
Ruby | 3.0.2 | [CVE-2021-41819](https://nvd.nist.gov/vuln/detail/CVE-2021-41819), [CVE-2021-41817](https://nvd.nist.gov/vuln/detail/CVE-2021-41817) | 3.1.2
Ruby | 2.7.4 | [CVE-2021-41819](https://nvd.nist.gov/vuln/detail/CVE-2021-41819), [CVE-2021-41817](https://nvd.nist.gov/vuln/detail/CVE-2021-41817) | 2.7.6

<h2>Sub-dependencies</h2>
<h3>JRuby 9.1.17.0</h3>

Sub-dependency | Version | CVEs | Minimum recommended version bump
-- | -- | -- | --
Bouncy Castle | 1.56 | [CVE-2018-1000180](https://nvd.nist.gov/vuln/detail/CVE-2018-1000180), [CVE-2020-15522](https://nvd.nist.gov/vuln/detail/CVE-2020-15522), [CVE-2017-13098](https://nvd.nist.gov/vuln/detail/CVE-2017-13098), [CVE-2020-26939](https://nvd.nist.gov/vuln/detail/CVE-2020-26939) | 1.70
JSON for Ruby | 1.8.3 | [CVE-2020-10663](https://nvd.nist.gov/vuln/detail/CVE-2020-10663) | 1.8.4
Rake | 10.4.2 | [CVE-2020-8130](https://nvd.nist.gov/vuln/detail/CVE-2020-8130) | 10.5.0
RDoc | 4.2.0 | [CVE-2021-31799](https://nvd.nist.gov/vuln/detail/CVE-2021-31799) | 6.4.0
SnakeYAML | 1.18 | [CVE-2017-18640](https://sap.blackducksoftware.com/api/vulnerabilities/CVE-2017-18640/overview) | 1.30

<h3>JRuby 9.2.20.1</h3>

Sub-dependency | Version | CVEs | Minimum recommended version bump
-- | -- | -- | --
Bouncy Castle | 1.68 | BDSA-2018-5235* (reintroduction of [CVE-2018-5382](https://nvd.nist.gov/vuln/detail/CVE-2018-5382)) | 1.70
Java Platform Standard Edition | 8u181 | [CVE-2018-3183](https://nvd.nist.gov/vuln/detail/CVE-2018-3183), [CVE-2018-3209](https://nvd.nist.gov/vuln/detail/CVE-2018-3209), [CVE-2018-3169](https://nvd.nist.gov/vuln/detail/CVE-2018-3169), [CVE-2018-3149](https://nvd.nist.gov/vuln/detail/CVE-2018-3149), [CVE-2018-3211](https://nvd.nist.gov/vuln/detail/CVE-2018-3211), [CVE-2018-14048](https://nvd.nist.gov/vuln/detail/CVE-2018-14048), [CVE-2018-13785](https://nvd.nist.gov/vuln/detail/CVE-2018-13785), [CVE-2018-3136](https://nvd.nist.gov/vuln/detail/CVE-2018-3136), [CVE-2018-3139](https://nvd.nist.gov/vuln/detail/CVE-2018-3139) | 8u281
RDoc | 6.1.2 | [CVE-2021-31799](https://nvd.nist.gov/vuln/detail/CVE-2021-31799) | 6.4.0
ruby/rdocv | 6.1.2 | [CVE-2021-31799](https://nvd.nist.gov/vuln/detail/cve-2021-31799) | 6.4.0

* "_Bouncy Castle contains a weak key-hash message authentication code (HMAC) that is only 16 bits long which can result in hash collisions. This is due to an error within the BKS version 1 keystore (BKS-V1) files and could lead to an attacker being able to affect the integrity of these files. Note: This issue issue occurs due to functionality that was re-introduced following the fix for CVE-2018-5382_"

**Comment by will-gant** [comment]
Just noting here that JRuby [v9.2.20.1](https://github.com/jruby/jruby/releases/tag/9.2.20.1) is already the latest patch of 9.2.x. It was released in December 2021 in response to another CVE, which suggests it's still getting security patches (though the release notes say "_We recommend that all JRuby 9.2 users upgrade._").

9.1.x, on the other hand, looks very much end-of-life. The buildpack is already consuming the latest patch available, v9.1.17.0, and this was [released back in April 2018](https://www.jruby.org/2018/04/23/jruby-9-1-17-0.html).

**Comment by arjun024** [comment]
Hi @will-gant, thank you filing the issue. We'll take a detailed look at this but I'd like to note down a couple of things before that:

* When a CVE is reported on a particular version, we make sure that the buildpack contains the updated (fixed) version. But, we do not remove the version where the CVE was reported regardless of the severity. Buildpacks thus ship multiple versions of a given dependency line, so a scan would always report CVEs, because buildpacks by design lets users select older versions of dependencies.

* The urgency with which we make buildpack releases depends on the CVE severity. If we get to know that the latest patch in a particular dependency line (e.g. ruby 3.0.x) is affected by a CVE reported as critical, we aim to make a buildpack release containing the patched version within 2 working days. In case of a low severity CVE, you would only see the new patch available in the next routine release (that happens monthly). In your `Top-level dependencies` table, I see that `3.0.4` and `2.7.6` are recommended bumps - they will be released in the upcoming release which is scheduled for next week. You can see that these versions are already available on the [develop branch](https://github.com/cloudfoundry/ruby-buildpack/blob/develop/manifest.yml) and you can build the buildpack yourself if you'd like to take that path. From the CVEs you listed I didn't find any high/critical CVE that affects the latest shipped patch - if there is one, let us know and we'll expedite the release.

* I agree that End-of-Life dependency lines should be removed and JRuby 9.1.x certainly seems EOL. I _think_ JRuby has no centralized portal detailing their End of Life timeline and it's difficult to know when a certain version line in EOL'ed. We'll look at removing 9.1.x in the upcoming release.

**Comment by will-gant** [comment]
Thanks for getting back to me so quickly, and for the indication on end-of-life dependency lines. To be clear, I realise older version lines need to be included, but I guess that's only so long as they're still being actively patched by their maintainers. 

When those version lines _are_ still being maintained, your timetable for consuming patches that tackle any CVEs sounds great. I think the awkward part is for version lines that haven't officially been condemned, but which are patched infrequently and whose _most recent_ patch has one or more outstanding CVEs. In that case, it's a matter of seeing if the maintainer will cut a new release for us.

Happily, if 9.1.x is going to be removed, that just means JRuby 9.2.20.1, which has four dependencies with a total of 12 CVEs. While not technically end-of-life, their latest patch was five months ago and [the release notes](https://github.com/jruby/jruby/releases/tag/9.2.20.1) made it sound like the end is nigh (_"We recommend that all JRuby 9.2 users upgrade"_). So I'm not sure how responsive they're going to be to a request to fix all of this.

On the question of the EOL status of 9.1.x, it looks like JRuby dropped the practice of announcing EOL for particular version lines a while ago. I had a good look for one for 9.1.x earlier today, and couldn't find anything.

**Comment by will-gant** [comment]
Just a note that I've updated the '_Minimum recommended version bump_' for ruby 3.0.2 from 3.1.1 to 3.1.2, as it turns out 3.1.1 also has a couple of CVEs:

* [CVE-2022-28738](https://www.ruby-lang.org/en/news/2022/04/12/double-free-in-regexp-compilation-cve-2022-28738/)
* [CVE-2022-28739](https://www.ruby-lang.org/en/news/2022/04/12/buffer-overrun-in-string-to-float-cve-2022-28739/)

**Comment by brayanhenao** [comment]
Hi @will-gant , after discussing it with the team we have decided to remove `JRuby 9.1.X` from the Ruby Buildpack since it no longer has security support.

The versions still present in the Buildpack (`9.2.20.1` and `9.3.4.0`) will continue to be updated as their security patch is released by JRuby team.

**Comment by will-gant** [comment]
Thanks. As there don't seem to be any (formal or informal) EOL announcements for JRuby version lines - I can't find any for 9.1.x - at some point a judgment call will have to be made on whether we regard 9.2.x as still being maintained. 

As mentioned, their security fixes for 9.2.x are pretty infrequent now, and their release notes advise upgrading. But I appreciate that's probably not quite enough to conclude that it's dead.
