### ISSUE TITLE
Make signing Contributing License Agreements easier

### ISSUE THREAD

**Issue by dijonkitchen** [cloudfoundry/ruby-buildpack#77]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
N/A

What version of the buildpack you are using?
N/A

If you were attempting to accomplish a task, what was it you were attempting to do?
Make a pull request (#76) and sign CLA. 

What did you expect to happen?
Online form/verification akin to https://code.facebook.com/cla 

What was the actual behavior?
Paper form/verification: https://www.cloudfoundry.org/governance/cff_individual_cla/

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @dijonkitchen,

Thanks for the feedback! The Cloud Foundry Foundation is aware that the current CLA submission process could be more convenient. I will make sure your concern is noted.

I'm going to close this issue for now though, because it cannot be addressed by the team that maintains CF buildpacks.
