### ISSUE TITLE
Is there a cflinuxsf4 buildpack with ruby 2.x?

### ISSUE THREAD

**Issue by pdornfel** [cloudfoundry/ruby-buildpack#798]
I am running a rails 5 and ruby 2.5.5 app and have a dependency that disallows me from upgrading to rails 6 and therefore I cannot upgrade to ruby 3.x. I wont be able to deploy going forward unless I use a cflinuxsf4 buildpack but no sf4 buildpacks include ruby 2.x. Is there somewhere I can get a cflinuxsf4 buildpack with ruby 2.x or can that be released or how can I do that myself?

This is for a client I manage and I really need to get this working. Any help is greatly appreciated!

Thank you!

**Comment by sophiewigmore** [comment]
Hey @pdornfel, the reason we don't support older versions of ruby on cflinuxfs4 is due to openssl incompatibilities between older Ruby versions and Jammy. Ruby versions less than 3.1 are not compatible with openssl 3, which is what jammy uses by default. 

Ruby 2.7 is already EOL and has been removed from the buildpack at this point, so we won't be adding workaround support for that version line, unfortunately. If you _really_ need this, you can try to [create a custom buildpack ](https://docs.cloudfoundry.org/buildpacks/custom.html#packaging-custom-buildpacks) based off of this buildpack, but add a version of Ruby 2.X that you need to the manifest.yml file, and then you'd need to add some type of logic to try to manually install `openssl 1.1` when Ruby 2.x is used if you can. I'm not entirely sure how straightforward that would be, and I honestly wouldn't recommend it. Alternatively, if you can figure out a way to compile Ruby 2.7 with openssl 3 support, you could get around having to install `openssl`, however, I'm not sure if that's actually even possible.

**Comment by sophiewigmore** [comment]
As far as I know, Ruby 2.x isn't really even usable with Ubuntu Jammy in general. It doesn't make sense for the buildpacks to do something that isn't even really doable in a regular local development.

**Comment by robdimsdale** [comment]
I'm going to close this issue as there has been no response in over a year.
